<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>mdown</string>
		<string>markdown</string>
		<string>markdn</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Markdown Notes</string>
	
	<key>patterns</key>
        <array>
        
			<!-- Plussed names  -->
            <dict>
                <key>name</key>
                <string>notes.person</string>

				<key>match</key>
				<string>\+[A-Za-z]+</string>
            </dict>     

			<!--  -->
            <dict>
                <key>match</key>
                <string>\b(?i:(hint|info|information))\b</string>
                <key>name</key>
                <string>info-token</string>
            </dict>                


			<!-- numbers -->
            <dict>
                <key>match</key>
                <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
                <key>name</key>
                <string>constant.numeric</string>
            </dict>       

			<!-- Quotes blue -->
            <dict>
                <key>name</key>
                <string>string.quoted.double</string>

                <key>begin</key>
				<string>"</string>

				<key>end</key>
				<string>"</string>
            </dict>       			
			
			<!-- Brackets gray  -->
            <dict>
                <key>name</key>
                <string>notes.brackets</string>

                <key>begin</key>
				<string>\(</string>

				<key>end</key>
				<string>\)</string>
            </dict>       

    


			<!-- match names -->
            <!-- <dict> 
			<key>name</key>
                <string>note.unused</string>				
                <key>match</key>                
				<string>\w \b([A-Z])\w+</string>
                <key>Captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>note.person-name</string>
					</dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>note.person-name</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>note.person-name</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>note.person-name</string>
					</dict>


				</dict>
            </dict>       -->
        

		

<!--markdown  -->

					<!-- heading  -->

					<dict>

					<key>begin</key>
					<string>(?:^|\G)[ ]{0,3}(#{1,6})\s*(?=[\S[^#]])</string>

					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown</string>
						</dict>
					</dict>

					<key>contentName</key>
					<string>entity.name.section.markdown</string>

					<key>end</key>
					<string>\s*(#{1,6})?$\n?</string>

					<key>name</key>
					<string>markup.heading.markdown</string>

				</dict>


				<!-- Blockquote   -->
					<dict>
					<key>begin</key>
					<string>(^|\G)[ ]{0,3}(&gt;) ?</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>beginning.punctuation.definition.quote.markdown</string>
						</dict>
					</dict>
					<key>name</key>
					<string>markup.quote.markdown</string>
					<!-- <key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block</string>
						</dict>
					</array> -->
					<key>while</key>
					<string>(^|\G)\s*(&gt;) ?</string>
				</dict>

	<!--lists  -->

						<dict>
							<key>begin</key>
							<string>(^|\G)([ ]{0,3})([*+-])([ ]{1,3}|\t)</string>
							<key>beginCaptures</key>
							<dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>beginning.punctuation.definition.list.markdown</string>
								</dict>
							</dict>

							<key>name</key>
							<string>markup.list.unnumbered.markdown</string>
							<key>while</key>
							<string>((^|\G)([ ]{4}|\t))|(^[ \t]*$)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)([ ]{0,3})([0-9]+\.)([ ]{1,3}|\t)</string>
							<key>beginCaptures</key>
							<dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>beginning.punctuation.definition.list.markdown</string>
								</dict>
							</dict>
							<key>name</key>
							<string>markup.list.numbered.markdown</string>
							<key>while</key>
							<string>((^|\G)([ ]{4}|\t))|(^[ \t]*$)</string>
						</dict> 



<!--markdown  -->

		</array>

<!-- repositories --> 



	<key>scopeName</key>
	<string>text.html.markdown</string>
	<key>uuid</key>
	<string>0A1D9874-B448-11D9-BD50-000D93B6E43C</string>
</dict>
</plist>
